# --- PostgreSQL ---
spring.datasource.url=jdbc:postgresql://localhost:5433/nexusq
spring.datasource.username=nexusq
spring.datasource.password=nexusq
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- Redis ---
spring.data.redis.host=localhost
spring.data.redis.port=6380

# --- Kafka ---
spring.kafka.bootstrap-servers=localhost:9092

# --- App ---
spring.application.name=nexusq
server.port=8080

# --- Actuator ---
management.endpoints.web.exposure.include=health,info,metrics,loggers,scheduledtasks,env,threaddump,beans
management.endpoint.health.show-details=always
management.health.kafka.enabled=true

#--- Logs --
logging.file.name=logs/nexusq.log